import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Logo from '../../public/imagens/Logo.svg'

export default function Cabecalho() {
return (
    <>
    <Head>
        <title>Unsplash</title>
        <meta name="description" content="Generated by Unsplash" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
        <main className={styles.cabecalho}>
            <Image className={styles.imagem} src={Logo} alt="Logo UnsplashBox"/>

            <button>Home</button>
            <button>Collections</button>
        </main>
    </>
);
}
